{"name": "test_calc_1[5-5-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 9", "trace": "input1 = 5, input2 = 5, output = 9\n\n    @ pytest.mark.parametrize(\"input1, input2, output\",\n                              [\n                                  (2,3,5),\n                                  (3,3,6),\n                                  (5,5,9)\n                              ]\n                              )\n    def test_calc_1(input1, input2, output):\n        result = sum(input1,input2)\n>       assert result == output\nE       assert 10 == 9\n\nTest_parameterization_demo.py:13: AssertionError"}, "parameters": [{"name": "input1", "value": "5"}, {"name": "input2", "value": "5"}, {"name": "output", "value": "9"}], "start": 1575222675524, "stop": 1575222675525, "uuid": "d2d6608c-f390-4b20-bb09-c002e2bc980c", "historyId": "a746a1245bd5baa059a65854fb49f4ce", "testCaseId": "5a181d683c3740351bdf2541f2217bf0", "fullName": "test_parameterization_demo#test_calc_1", "labels": [{"name": "suite", "value": "test_parameterization_demo"}, {"name": "host", "value": "iMac.local"}, {"name": "thread", "value": "66493-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_parameterization_demo"}]}